import { describe, expect, it, vi } from 'vitest';
import { buildBrowserQuestions, buildBrowserState, parseBrowserChoice, assertFresh, StalePageError, guardBrowserAction, rankActions, SNAPSHOT_SCRIPT, type BrowserSnapshot } from '../src/index.js';
const snapshot: BrowserSnapshot = { url: 'https://example.com', title: 'Example', visibleText: 'Search docs', fingerprint: 'abc', actions: [{ id: 'e1', node: 1, kind: 'click', label: 'Search', role: 'button' }, { id: 'e2', node: 2, kind: 'fill', label: 'Query', role: 'textbox' }, { id: 'wait', kind: 'wait', label: 'Wait' }] };
describe('fast browser core', () => {
  it('builds dynamic compatible operation and target questions', () => { const questions = buildBrowserQuestions(snapshot, 'search docs'); expect(questions.operation.type).toBe('choice'); expect(questions.click_target).toBeDefined(); expect(questions.fill_target).toBeDefined(); expect(buildBrowserState(snapshot, 'search docs')).toContain('e1'); });
  it('ranks relevant observed controls before unrelated page links', () => { const many = { ...snapshot, actions: [{ id: 'noise', kind: 'click' as const, label: 'Account settings' }, { id: 'docs', kind: 'click' as const, label: 'JavaScript documentation' }, ...snapshot.actions] }; expect(rankActions(many, 'open JavaScript documentation')[0]?.id).toBe('docs'); });
  it('accepts only targets compatible with the selected operation', () => { const result = parseBrowserChoice(snapshot, { answers: { operation: { type: 'choice', choice: 'CLICK', confidence: .9, probabilities: { CLICK: .9 } }, click_target: { type: 'choice', choice: 'e1', confidence: .8, probabilities: { e1: .8 } } } }); expect(result).toMatchObject({ operation: 'CLICK', target: 'e1', confidence: .8 }); });
  it('rejects stale page decisions', () => { expect(() => assertFresh(snapshot, 'abc')).not.toThrow(); expect(() => assertFresh(snapshot, 'changed')).toThrow(StalePageError); });
  it('calls the authenticated guard daemon', async () => { const fetcher = vi.fn(async () => new Response(JSON.stringify({ decision: 'deny', latencyMs: 4 }), { status: 200 })); const request = { workspace: 'C:\\demo', provenance: 'browser-sidecar' as const, page: { url: snapshot.url, title: snapshot.title, visibleText: snapshot.visibleText }, action: { id: 'e1', kind: 'click' as const, label: 'Delete', pageFingerprint: snapshot.fingerprint, workspace: 'C:\\demo' } }; expect((await guardBrowserAction('http://127.0.0.1:1234', 'token', request, fetcher as typeof fetch)).decision).toBe('deny'); expect(fetcher).toHaveBeenCalledOnce(); });
  it('ships one atomic snapshot script without screenshots', () => { expect(SNAPSHOT_SCRIPT).toContain('querySelectorAll'); expect(SNAPSHOT_SCRIPT).not.toContain('captureScreenshot'); });
});
